apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- includeCRDs: true
  name: argo-rollouts
  namespace: argo-rollouts
  releaseName: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 2.39.1