apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: kyverno
  namespace: kyverno
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno
  includeCRDs: true
  valuesFile: prod-values.yaml
  version: 3.4.1
