kyverno:
  grafana:
    enabled: true
    namespace: monitoring
    labels:
      grafana-dashboard: kyverno-dashboard
  service-monitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: kube-prometheus-stack
