apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: akuity
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2ekNDQXFlZ0F3SUJBZ0lVRTNMV2xRNHU5eHNRUWRLSFhMbXRJaURqa05zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1F6RWNNQm9HQTFVRUNoTVRaWGgwWlhKdVlXd3RjMlZqY21WMGN5NXBiekVqTUNFR0ExVUVBeE1hWTJWeQpkQzF0WVc1aFoyVnlMV0pwZEhkaGNtUmxiaTEwYkhNd0hoY05Nall3TVRJMk1qSXhNekk0V2hjTk1qWXdOREkyCk1qSXhNekk0V2pCRE1Sd3dHZ1lEVlFRS0V4TmxlSFJsY201aGJDMXpaV055WlhSekxtbHZNU013SVFZRFZRUUQKRXhwalpYSjBMVzFoYm1GblpYSXRZbWwwZDJGeVpHVnVMWFJzY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU1wcTZnYVR1ZHVOVnVJb1J1ZXE1Q1ErR2JaUE5DWG81M1NtdFovUGt0aElhTmZoCmUrY1FKUmEvbVhMaHRwMUlSWmJkWko1aFRwU3I3VTFKMitaU1NGbnBFc0F4bWhYY0xzQkFVVmE0bFE5WkRYY3gKaHZBb0RlWnBtQnNzdFVybW00bVJKWEVqc1JicmNmbC9tckFmNGNVTk5DZ1JxUzRLK2RvVDE3b3Vrcklzc2RuaAplVWk0SmFJUjh1MXZiSlZvNVF1cEZPbEo3UFdGV2dRZHkyaWYvNmlwb3FZUHRXVk5LL2pTR3lYbnREb3I3SlB5CjgvNkRGblFmcW9KVCtRSEFGQ1dJWHNwREl5cmVuUC9GZGpVZzVIUklMWmttellKTTY4aGZkQ05aVTY4R1hTTHcKOG5kSTJPdXVlSUxZY3hMUW5hSklRelZXTVRpemJ0dElDdmdZb09zQ0F3RUFBYU9CcWpDQnB6QU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUzMWJVOXIrSGdGZWg5MVZwClZ6ODVtRVpYWEdjd1pRWURWUjBSQkY0d1hJSTNZbWwwZDJGeVpHVnVMWE5rYXkxelpYSjJaWEl1WlhoMFpYSnUKWVd3dGMyVmpjbVYwY3k1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJSmJHOWpZV3hvYjNOMGh3Ui9BQUFCaHhBQQpBQUFBQUFBQUFBQUFBQUFBQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVNyNnFRRmhBdGhJVWFqZ2N5CmREOUlndEsyZmtHM1BFaE9MU2NxUmZDT1hUNFVKdUpWdkszVHFLNVR2R0ZLL0JHcTNlK1JOWWh4eXJxdnkxa0kKY3VVOTNtdVd3MFZSRTBKOUJjcjNueURRR1R6S3ZDMklCVzNEamxFY2MrM2NWOVgzLzlwSlA0eWd3amxXcjE0LwpGeHdGUmw0QXdzOG1zQVRITTZqQ3BYazlMb1NNYUlxcFVOb0REOGs3T3MwYXJmRUIwYUw4YkVWNEdmSTZXaWp1CjFPcS85Y1pDQlFuTWlUYU5SZTBHS04zaTNiWkJEQXJWSk5aSGoyMENOcHVMZmZFNk9hRWJHdFZjbk9menpBMTAKa0FiMi9PNzI5WUJKa0I2Rm0xNkpoR2VlZkFkVStQMWJSWm96WVZNR2VQSys2TUhsYXpuOTB2aDdobUowTHpGRApuTjZ6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      organizationID: 9e7eec71-0b50-4861-aa5a-aab3006ad710s
      projectID: 7a7bca4a-3e6f-43cd-8b53-b3a200adabf8
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: akuity-kargo
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2ekNDQXFlZ0F3SUJBZ0lVRTNMV2xRNHU5eHNRUWRLSFhMbXRJaURqa05zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1F6RWNNQm9HQTFVRUNoTVRaWGgwWlhKdVlXd3RjMlZqY21WMGN5NXBiekVqTUNFR0ExVUVBeE1hWTJWeQpkQzF0WVc1aFoyVnlMV0pwZEhkaGNtUmxiaTEwYkhNd0hoY05Nall3TVRJMk1qSXhNekk0V2hjTk1qWXdOREkyCk1qSXhNekk0V2pCRE1Sd3dHZ1lEVlFRS0V4TmxlSFJsY201aGJDMXpaV055WlhSekxtbHZNU013SVFZRFZRUUQKRXhwalpYSjBMVzFoYm1GblpYSXRZbWwwZDJGeVpHVnVMWFJzY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU1wcTZnYVR1ZHVOVnVJb1J1ZXE1Q1ErR2JaUE5DWG81M1NtdFovUGt0aElhTmZoCmUrY1FKUmEvbVhMaHRwMUlSWmJkWko1aFRwU3I3VTFKMitaU1NGbnBFc0F4bWhYY0xzQkFVVmE0bFE5WkRYY3gKaHZBb0RlWnBtQnNzdFVybW00bVJKWEVqc1JicmNmbC9tckFmNGNVTk5DZ1JxUzRLK2RvVDE3b3Vrcklzc2RuaAplVWk0SmFJUjh1MXZiSlZvNVF1cEZPbEo3UFdGV2dRZHkyaWYvNmlwb3FZUHRXVk5LL2pTR3lYbnREb3I3SlB5CjgvNkRGblFmcW9KVCtRSEFGQ1dJWHNwREl5cmVuUC9GZGpVZzVIUklMWmttellKTTY4aGZkQ05aVTY4R1hTTHcKOG5kSTJPdXVlSUxZY3hMUW5hSklRelZXTVRpemJ0dElDdmdZb09zQ0F3RUFBYU9CcWpDQnB6QU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUzMWJVOXIrSGdGZWg5MVZwClZ6ODVtRVpYWEdjd1pRWURWUjBSQkY0d1hJSTNZbWwwZDJGeVpHVnVMWE5rYXkxelpYSjJaWEl1WlhoMFpYSnUKWVd3dGMyVmpjbVYwY3k1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJSmJHOWpZV3hvYjNOMGh3Ui9BQUFCaHhBQQpBQUFBQUFBQUFBQUFBQUFBQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVNyNnFRRmhBdGhJVWFqZ2N5CmREOUlndEsyZmtHM1BFaE9MU2NxUmZDT1hUNFVKdUpWdkszVHFLNVR2R0ZLL0JHcTNlK1JOWWh4eXJxdnkxa0kKY3VVOTNtdVd3MFZSRTBKOUJjcjNueURRR1R6S3ZDMklCVzNEamxFY2MrM2NWOVgzLzlwSlA0eWd3amxXcjE0LwpGeHdGUmw0QXdzOG1zQVRITTZqQ3BYazlMb1NNYUlxcFVOb0REOGs3T3MwYXJmRUIwYUw4YkVWNEdmSTZXaWp1CjFPcS85Y1pDQlFuTWlUYU5SZTBHS04zaTNiWkJEQXJWSk5aSGoyMENOcHVMZmZFNk9hRWJHdFZjbk9menpBMTAKa0FiMi9PNzI5WUJKa0I2Rm0xNkpoR2VlZkFkVStQMWJSWm96WVZNR2VQSys2TUhsYXpuOTB2aDdobUowTHpGRApuTjZ6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      organizationID: 9e7eec71-0b50-4861-aa5a-aab3006ad710s
      projectID: 7a7bca4a-3e6f-43cd-8b53-b3a200adabf8
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-addons-creds
  namespace: akuity
  labels:
   argocd.argoproj.io/secret-type: repository
   akuity.io/secret-sync: "true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: "e9d0506a-6d68-45f8-af88-b3a3005748b8"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-helm-prom-stack
  namespace: akuity-kargo
  labels:
   kargo.akuity.io/cred-type: git
   kargo.akuity.io/secret-sync: "kargo-shared-resources"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: "4fff35e9-20c1-4a3e-bd27-b3a3004b5f1a"
