apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: akuity
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmakNDQW1hZ0F3SUJBZ0lVYmNGajFQQjRBbVduYTY3dXUyRFdQS2RHSUZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1F6RWNNQm9HQTFVRUNoTVRaWGgwWlhKdVlXd3RjMlZqY21WMGN5NXBiekVqTUNFR0ExVUVBeE1hWTJWeQpkQzF0WVc1aFoyVnlMV0pwZEhkaGNtUmxiaTEwYkhNd0hoY05Nall3TVRJMk1qSXhNek16V2hjTk1qWXdOREkyCk1qSXhNek16V2pBQU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNHF5Y0VjMHMKbUt0Tjk1UzV4TmhJckRmVHZtN0xUd2lVbS9sWS80MDRBcStWTXJleHRXSkxYWXllSUxKdGFEaldWdnB4WTRrbgpjM0pIcnBEaTE2L1lpdUpTM3hvNkxQMlI4dTM0eW55V1EyWUdFUkFwYmxvUk9QMlNteFBocTRReFk2TU81OGtBCkl5alV2eEtVL0hmMTJxM050UmZpNFExVHc3Y01EMnUyWEtIQjNxTXFhV2xwandOLzFKdXBLVEJPbXVPYUhWbkYKVk44cEU3dkZZUytrM3ZwZTZrRGI4dHRSdEpDQVhkUFRwbHArQWdoL0NMNlQ0VlJGQlMyelRqRlhZS2plTEhGRAptay9SeTVxM0REczUwNmhodVIrUHFyK0FGMTNURDhwWjRKMUxEdC9hOWlnc1MyNnYzMmJ5Nmt2K29yU0dMUkkrClZweC92cHJHeWEwQ1R3SURBUUFCbzRHc01JR3BNQTRHQTFVZER3RUIvd1FFQXdJRm9EQU1CZ05WSFJNQkFmOEUKQWpBQU1COEdBMVVkSXdRWU1CYUFGSmluN2JDTlJFbGdCVDRjeXZiOFNUdHNTRms4TUdnR0ExVWRFUUVCL3dSZQpNRnlDTjJKcGRIZGhjbVJsYmkxelpHc3RjMlZ5ZG1WeUxtVjRkR1Z5Ym1Gc0xYTmxZM0psZEhNdWMzWmpMbU5zCmRYTjBaWEl1Ykc5allXeUNDV3h2WTJGc2FHOXpkSWNFZndBQUFZY1FBQUFBQUFBQUFBQUFBQUFBQUFBQUFUQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb0NCaXNlMVBtU2NCNDliQXJnUXQ0bGNlL2ZHUVhEYzdCYVhyMU9KOQp1K1JQc0lnMzZNLzlCMjAyZmJoajNNU1RQbW5IUTFwVStLcncxMHJkeCtBaVZ3RFRFOHUyelFVRXJOVExxbW5DClFsd2ZtdkxFWE1tbTlOeTFCTGNCMk1uVWMwb0lIcDNPVUFGMWxIaVg1RkJraThQWUtFcDMxZ0VNZFYvd2FsQ3QKcW5ueVM5a1VrWTAxOXFGZFBDYnUwMWJGay9JcXNDcDIzQ3JIWDFhdnNlQmtEMU5XaEN2MHAxWXY3QnBFUEg4dAoyWWl1b0lFSEJWdFJZZTVkRlVxYXdBVy92eW4yZUNuWUdtQStmVjhKbnFpaUFPZmJ6NjRBc2VJOHF3SVFRcWZ2Cmp3ZmxIKyt0YXBNb1FPQlB2ZXJ5akJUbXlFSXVaZ0R4R0hobGhLTkhtSnVlR0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo=
      organizationID: 9e7eec71-0b50-4861-aa5a-aab3006ad710s
      projectID: 7a7bca4a-3e6f-43cd-8b53-b3a200adabf8
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: akuity-kargo
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmakNDQW1hZ0F3SUJBZ0lVYmNGajFQQjRBbVduYTY3dXUyRFdQS2RHSUZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1F6RWNNQm9HQTFVRUNoTVRaWGgwWlhKdVlXd3RjMlZqY21WMGN5NXBiekVqTUNFR0ExVUVBeE1hWTJWeQpkQzF0WVc1aFoyVnlMV0pwZEhkaGNtUmxiaTEwYkhNd0hoY05Nall3TVRJMk1qSXhNek16V2hjTk1qWXdOREkyCk1qSXhNek16V2pBQU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNHF5Y0VjMHMKbUt0Tjk1UzV4TmhJckRmVHZtN0xUd2lVbS9sWS80MDRBcStWTXJleHRXSkxYWXllSUxKdGFEaldWdnB4WTRrbgpjM0pIcnBEaTE2L1lpdUpTM3hvNkxQMlI4dTM0eW55V1EyWUdFUkFwYmxvUk9QMlNteFBocTRReFk2TU81OGtBCkl5alV2eEtVL0hmMTJxM050UmZpNFExVHc3Y01EMnUyWEtIQjNxTXFhV2xwandOLzFKdXBLVEJPbXVPYUhWbkYKVk44cEU3dkZZUytrM3ZwZTZrRGI4dHRSdEpDQVhkUFRwbHArQWdoL0NMNlQ0VlJGQlMyelRqRlhZS2plTEhGRAptay9SeTVxM0REczUwNmhodVIrUHFyK0FGMTNURDhwWjRKMUxEdC9hOWlnc1MyNnYzMmJ5Nmt2K29yU0dMUkkrClZweC92cHJHeWEwQ1R3SURBUUFCbzRHc01JR3BNQTRHQTFVZER3RUIvd1FFQXdJRm9EQU1CZ05WSFJNQkFmOEUKQWpBQU1COEdBMVVkSXdRWU1CYUFGSmluN2JDTlJFbGdCVDRjeXZiOFNUdHNTRms4TUdnR0ExVWRFUUVCL3dSZQpNRnlDTjJKcGRIZGhjbVJsYmkxelpHc3RjMlZ5ZG1WeUxtVjRkR1Z5Ym1Gc0xYTmxZM0psZEhNdWMzWmpMbU5zCmRYTjBaWEl1Ykc5allXeUNDV3h2WTJGc2FHOXpkSWNFZndBQUFZY1FBQUFBQUFBQUFBQUFBQUFBQUFBQUFUQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb0NCaXNlMVBtU2NCNDliQXJnUXQ0bGNlL2ZHUVhEYzdCYVhyMU9KOQp1K1JQc0lnMzZNLzlCMjAyZmJoajNNU1RQbW5IUTFwVStLcncxMHJkeCtBaVZ3RFRFOHUyelFVRXJOVExxbW5DClFsd2ZtdkxFWE1tbTlOeTFCTGNCMk1uVWMwb0lIcDNPVUFGMWxIaVg1RkJraThQWUtFcDMxZ0VNZFYvd2FsQ3QKcW5ueVM5a1VrWTAxOXFGZFBDYnUwMWJGay9JcXNDcDIzQ3JIWDFhdnNlQmtEMU5XaEN2MHAxWXY3QnBFUEg4dAoyWWl1b0lFSEJWdFJZZTVkRlVxYXdBVy92eW4yZUNuWUdtQStmVjhKbnFpaUFPZmJ6NjRBc2VJOHF3SVFRcWZ2Cmp3ZmxIKyt0YXBNb1FPQlB2ZXJ5akJUbXlFSXVaZ0R4R0hobGhLTkhtSnVlR0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo=
      organizationID: 9e7eec71-0b50-4861-aa5a-aab3006ad710s
      projectID: 7a7bca4a-3e6f-43cd-8b53-b3a200adabf8
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-addons-creds
  namespace: akuity
  labels:
   argocd.argoproj.io/secret-type: repository
   akuity.io/secret-sync: "true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: "e9d0506a-6d68-45f8-af88-b3a3005748b8"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-helm-prom-stack
  namespace: akuity-kargo
  labels:
   kargo.akuity.io/cred-type: git
   kargo.akuity.io/secret-sync: "kargo-shared-resources"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: "4fff35e9-20c1-4a3e-bd27-b3a3004b5f1a"
