admissionController:
  serviceMonitor:
    enabled: false
    namespace: kyverno
    additionalLabels:
      release: kube-prometheus-stack

backgroundController:
  serviceMonitor:
    enabled: false
    namespace: kyverno
    additionalLabels:
      release: kube-prometheus-stack

cleanupController:
  serviceMonitor:
    enabled: false
    namespace: kyverno
    additionalLabels:
      release: kube-prometheus-stack

reportsController:
  serviceMonitor:
    enabled: false
    namespace: kyverno
    additionalLabels:
      release: kube-prometheus-stack

grafana:
  enabled: false
  namespace: monitoring
  labels:
    grafana-dashboard: kyverno-dashboard
